name: app_3d_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans_Condensed-ExtraLight.ttf
        - asset: assets/fonts/NotoSans_Condensed-Light.ttf
        - asset: assets/fonts/NotoSans_Condensed-Medium.ttf
        - asset: assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSans_Condensed-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans_ExtraCondensed-Black.ttf

  assets:
    - assets/icons/
    - assets/img/
    - .env