name: app_3d_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cloud_firestore: ^6.2.0
  file_picker: ^11.0.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.6.0
  firebase_storage: ^13.3.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans_Condensed-ExtraLight.ttf
        - asset: assets/fonts/NotoSans_Condensed-Light.ttf
        - asset: assets/fonts/NotoSans_Condensed-Medium.ttf
        - asset: assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: assets/fonts/NotoSans_Condensed-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans_ExtraCondensed-Black.ttf

  assets:
    - assets/icons/
    - assets/img/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logoApp.jpg"
  remove_alpha_ios: true